### ISSUE TITLE
Maybe it's simple, but not safe.

### ISSUE THREAD

**Issue by Botnary** [Pixelfck/SymmetricEncryption#1]
Check out this discussion on stack exchange:
http://security.stackexchange.com/questions/74111/security-review-is-this-php-mcrypt-wrapper-class-safe

**Comment by Pixelfck** [comment]
Thanks for the link. I will see that the issues get addressed.

**Comment by Pixelfck** [comment]
All mentioned issues have been addressed:
- Added constant time signature verification as to prevent possible timing attacks (_bullet 1_),
- Having Multibyte String string function overloading active now results in a E_USER_ERROR (_bullet 2_),
- Removed build-in support for compression (_bullet 3_),
- Made sure the library now uses AES-128 instead of AES-256 (_bullet 5_).

Two mentioned design decisions have not been changed: 
- PBKDF2_BLOCK_COUNT is still 1: if more output bytes (dkLen) are requested than the native hash function supplies, the cost for the defender is increased considerably (multiple key derivations with thousands of iterations) while not increasing the cost for the attacker, because he can verify correctness of his password guess after one key was derived, he doesn't need both (_bullet 4_).
- The key derivation in the HKDF-expand is called twice, once for each key, using the info element to distinguish between the two. This is how the expand step is intended to function (_bullet 6_).
